# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: WoWAchievements_development
  pool: 5
  username: root
  password:
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: WoWAchievements_test
  pool: 5
  username: root
  password:
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: WoWAchievements_production
  pool: 5
  username: root
  password:
  host: localhost